image: docker:latest
services:
  - docker:dind

variables:
  WORK_DIR: ${CI_PROJECT_NAME}
  BRANCH: ${CI_COMMIT_REF_NAME}
  REGISTRY: registry.gitlab.com/troydo42/gro-api

stages:
  - build
  - deploy

build job:
  stage: build
  script:
      - docker login -u troydo42 -p $PASS registry.gitlab.com
      - docker build -t $REGISTRY .
      - docker push $REGISTRY

deploy job:
  stage: deploy
  script:
      - docker login -u johandurancerdas -p $PASS registry.gitlab.com
      - docker pull $REGISTRY
      - docker run --name=$BRANCH -p 80:8080 -i $REGISTRY npm run ci
    
