"""empty message

Revision ID: 14072ea07e58
Revises: c44317517fdd
Create Date: 2018-05-06 23:43:59.750682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14072ea07e58'
down_revision = 'c44317517fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('annual_income', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('average_current_balance', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('emp_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputs', 'emp_length')
    op.drop_column('inputs', 'average_current_balance')
    op.drop_column('inputs', 'annual_income')
    # ### end Alembic commands ###
