"""empty message

Revision ID: 24ae066321e8
Revises: 09f5a7045eed
Create Date: 2018-06-04 19:51:18.149480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ae066321e8'
down_revision = '09f5a7045eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
