"""empty message

Revision ID: 57d4b960a643
Revises: 07f699d4a893
Create Date: 2019-03-29 13:12:36.718541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d4b960a643'
down_revision = '07f699d4a893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banking_tokens')
    # ### end Alembic commands ###
