"""empty message

Revision ID: 581f5d8e3e04
Revises: 
Create Date: 2018-03-01 15:42:03.368136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581f5d8e3e04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'admin')
    op.drop_column('companies', 'active')
    ### end Alembic commands ###
