"""empty message

Revision ID: 5add1e65612b
Revises: 7bb4b2fd37c5
Create Date: 2018-06-15 12:15:40.189621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5add1e65612b'
down_revision = '7bb4b2fd37c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('deling_2yrs', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('delinq_2yrs_zero', sa.Boolean(), nullable=True))
    op.add_column('inputs', sa.Column('inq_last_6mths', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('last_deling_none', sa.Boolean(), nullable=True))
    op.add_column('inputs', sa.Column('last_major_derog_none', sa.Boolean(), nullable=True))
    op.add_column('inputs', sa.Column('payment_inc_ratio', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('pub_rec', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('pub_rec_zero', sa.Boolean(), nullable=True))
    op.add_column('inputs', sa.Column('short_emp', sa.Boolean(), nullable=True))
    op.drop_column('inputs', 'totHiCredLim')
    op.drop_column('inputs', 'percentBcGt75')
    op.drop_column('inputs', 'totalBalIl')
    op.drop_column('inputs', 'numRevAccts')
    op.drop_column('inputs', 'iLUtil')
    op.drop_column('inputs', 'numIlTl')
    op.drop_column('inputs', 'totCurBal')
    op.drop_column('inputs', 'numBcTl')
    op.drop_column('inputs', 'mtgPayment')
    op.drop_column('inputs', 'totalIlHighCreditLimit')
    op.drop_column('inputs', 'bcUtil')
    op.drop_column('inputs', 'dtiJoint')
    op.drop_column('inputs', 'totalBalExMort')
    op.drop_column('inputs', 'totalAcc')
    op.drop_column('inputs', 'totalBcLimit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('totalBcLimit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('totalAcc', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('totalBalExMort', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('dtiJoint', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('bcUtil', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('totalIlHighCreditLimit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('mtgPayment', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('numBcTl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('totCurBal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('numIlTl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('iLUtil', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('numRevAccts', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('totalBalIl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('percentBcGt75', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('inputs', sa.Column('totHiCredLim', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('inputs', 'short_emp')
    op.drop_column('inputs', 'pub_rec_zero')
    op.drop_column('inputs', 'pub_rec')
    op.drop_column('inputs', 'payment_inc_ratio')
    op.drop_column('inputs', 'last_major_derog_none')
    op.drop_column('inputs', 'last_deling_none')
    op.drop_column('inputs', 'inq_last_6mths')
    op.drop_column('inputs', 'delinq_2yrs_zero')
    op.drop_column('inputs', 'deling_2yrs')
    # ### end Alembic commands ###
