"""empty message

Revision ID: 77350fa637d8
Revises: ceaf698d9bb9
Create Date: 2018-10-18 14:00:21.317413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77350fa637d8'
down_revision = 'ceaf698d9bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('annual_revenue', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('established_date', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('industry', sa.Enum('Agri', 'Manu', name='industrytype'), nullable=True))
    op.add_column('companies', sa.Column('structure', sa.Enum('S', 'GP', 'C', 'LLC', 'SLLC', name='structuretype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'structure')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'established_date')
    op.drop_column('companies', 'annual_revenue')
    # ### end Alembic commands ###
