"""empty message

Revision ID: c48cbff391b5
Revises: 24ae066321e8
Create Date: 2018-06-06 14:50:53.866818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48cbff391b5'
down_revision = '24ae066321e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily balance', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily balance', 'bank_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
