"""empty message

Revision ID: ceaf698d9bb9
Revises: 1ebb58da7049
Create Date: 2018-10-18 12:07:12.407902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaf698d9bb9'
down_revision = '1ebb58da7049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_phone', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('email_address', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'password')
    op.drop_column('companies', 'email_address')
    op.drop_column('companies', 'company_phone')
    # ### end Alembic commands ###
