"""empty message

Revision ID: e62cc0a30270
Revises: 14072ea07e58
Create Date: 2018-05-07 00:08:17.878989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62cc0a30270'
down_revision = '14072ea07e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('bcUtil', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('dtiJoint', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('iLUtil', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('mtgPayment', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('numBcTl', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('numIlTl', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('numRevAccts', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('openAcc', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('percentBcGt75', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('revolBal', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('revolUtil', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('totCurBal', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('totHiCredLim', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('totalAcc', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('totalBalExMort', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('totalBalIl', sa.Integer(), nullable=True))
    op.add_column('inputs', sa.Column('totalBcLimit', sa.Float(), nullable=True))
    op.add_column('inputs', sa.Column('totalIlHighCreditLimit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputs', 'totalIlHighCreditLimit')
    op.drop_column('inputs', 'totalBcLimit')
    op.drop_column('inputs', 'totalBalIl')
    op.drop_column('inputs', 'totalBalExMort')
    op.drop_column('inputs', 'totalAcc')
    op.drop_column('inputs', 'totHiCredLim')
    op.drop_column('inputs', 'totCurBal')
    op.drop_column('inputs', 'revolUtil')
    op.drop_column('inputs', 'revolBal')
    op.drop_column('inputs', 'percentBcGt75')
    op.drop_column('inputs', 'openAcc')
    op.drop_column('inputs', 'numRevAccts')
    op.drop_column('inputs', 'numIlTl')
    op.drop_column('inputs', 'numBcTl')
    op.drop_column('inputs', 'mtgPayment')
    op.drop_column('inputs', 'iLUtil')
    op.drop_column('inputs', 'dtiJoint')
    op.drop_column('inputs', 'bcUtil')
    # ### end Alembic commands ###
